image: docker:latest

stages:
  - build

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

DEV build:
  stage: build
  only:
    - /^.*--dev$/
  except:
    - branches
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}" .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}"
  environment:
    name: DEV

PRD build:
  stage: build
  only:
    - /^v.*$/
  except:
    - branches
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}" .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}"
  environment:
    name: PRD
